IDR/idr-utils

.travis.yml, pyidr/file_pattern.py, pyidr/screenio.py, pyidr/study_parser.py, scripts/annotate/missing_image_annotations.py, scripts/annotate/missing_well_annotations.py, scripts/celery/calc.py, scripts/celery/get_failed.py, scripts/check_screen.py, scripts/gen_screens_0016_0036/make_screen.py, scripts/git-restore-mtime-bare.py, scripts/nginx_parse.py, scripts/stats.py, scripts/travis-check.py, scripts/tsv_plates.py, setup.py, test/test_screenio.py
Upgrade the IDR utility scripts to be Python 3 compatible and fix the study parser utility with OMERO 5.6.
- 993d8b8 was originally generated by running `futurize -w -n .`
- the other commits were tested while updating the annotations on `prod80`. The outcome of these changes can be tested on a local server by running
```
$ git clone git://github.com/sbesson/idr-utils -b python3
$ /opt/omero/server/venv3/bin/omero login public@localhost -w public
$ find /uod/idr/metadata/ -type f -name '*study.txt' | sort | xargs /opt/omero/server/venv3/bin/python pyidr/study_parser.py --check -q
```
The `stats.py` and other scripts should be minimally functional but have not been tested yet and might need additional tweaks outside the scope of this PR
=> Python 3 support

.travis.yml, pyidr/study_parser.py, test/test_study_parser.py
Minor cleanups while reviewing the publications associated with IDR datasets:
- add support for DOIs either under the `prefix/suffix` form e.g `10.17867/10000134` or the URL form e.g. https://doi.org/10.17867/10000134 in the study file
- improve the strictness of the DOI prefix/suffix regex parsing
- add unit tests for the DOI parsing and use `pytest`
=> Improve DOI parsing in study file

pyidr/study_parser.py
In some cases, IDR studies might be also be available from EMPIAR so we want to be able to cross-reference an EMPIAR accessions in the same way as BioImageArchive/BioStudies.
This change to the study parser allows to recognize `Study EMPIAR Accession` as a new valid key in the study file and will create a new `EMPIAR Accession` key with  `EMPIAR-<id> https://www.ebi.ac.uk/pdbe/emdb/empiar/entry/<id>` as a value in the study map.
/cc @francesw @dominikl likely to be tested in the context of `idr0083`
=> Add support for EMPIAR accessions

scripts/stats.py
As reported by @dominikl, this PR amends the `stats.py` generation script to match a few architectural changes since `prod80`:
- fix the script followin the Python2 -> Python 3 upgrade (`len`, `fileinput`)
- handle the migration of the utility scripts under `idr-utils`
- add logging to the scripts
These changes can be tested against the live IDR from a checkout of https://github.com/IDR/idr-metadata and a Python 3 virtual environment with OMERO.py installed.
```
cd /uod/idr/metadata
source ~/venvs/omeropy/bin/activate
python idr-utils/scripts/stats.py
```
=> Fix stats generation script

pyidr/study_parser.py
Many studies include a reference to an external URL, usually the homepage of the project but this information is lost in the live resource.
This change should transform each tab-separated value in the study file as a key/value pair in the top-level study annotation
=> Add support for the external URL in the study annotation in the resource

pyidr/study_parser.py
- adds `Study Key Words` to the list of known keys so that recent study files do not throw a warning
- do not throw an ERROR when annotations/description are edited by `study_parser.py --set` - fixes an issue raised by @will-moore @dominikl
=> Minor study parser improvements

setup.py
https://travis-ci.org/github/IDR/idr-metadata/builds/712093394 highlights some incompatibilities
```
Traceback (most recent call last):
File "idr-utils/scripts/travis-check.py", line 11, in <module>
import pandas
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas/__init__.py", line 56, in <module>
from pandas.util.nosetester import NoseTester
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pandas/util/nosetester.py", line 13, in <module>
from numpy.testing import nosetester
ImportError: cannot import name 'nosetester'
```
With the migration to PYthon3, we should be able to consume the stable `1.x` version of pandas
=> Uncap pandas version

scripts/stats.py
- Remove the screen rendering option (replaced by the render CLI plugin)
- Rename the `stat_screens` method since it's for all top-level containers.
- Use `yaml.safe_load` to avoid a deprecation warning
- Remove the `screen` argument and corresponding `stat_plates` method since it doesn't seem to work, it always returns 0
```
$ ./idr-utils/scripts/stats.py idr0001-graml-sysgro/screenA
Using session for public@idr.openmicroscopy.org:4064. Idle timeout: 10 min. Current group: Public
Plate | PID | Wells | Images
-------+-----+-------+--------
Total |     | 0     | 0
(1 row)
$ ./idr-utils/scripts/stats.py  idr0002-heriche-condensation/screenA
Using session for public@idr.openmicroscopy.org:4064. Idle timeout: 10 min. Current group: Public
Plate | PID | Wells | Images …
```
=> Cleanup stats.py before more refactoring

scripts/stats.py
`stats.py` now defaults to printing out something that can be appended to [`studies.tsv`](https://github.com/IDR/idr.openmicroscopy.org/blob/master/_data/studies.tsv), e.g.:
```
omero login
./idr-utils/scripts/stats.py idr0048-abdeladim-chroms >> studies.tsv
```
This includes the fs usage calculation which may take a very long time or may crash the server. To disable the fs usage calculation:
```
./idr-utils/scripts/stats.py --disable-fsusage idr0048-abdeladim-chroms >> studies.tsv
```
If you want a human readable output pass `--format string` (`string` refers to a pandas output format).
=> Refactor stats.py

scripts/stats.py
Follow-up of #16, this fixes the calculation of the `Sets` column to use the return of the query. 
Previously, the value of `nexpected` was used which corresponds to the number of rows in the `filePaths.tsv` or `plates.tsv`- see https://github.com/IDR/idr.openmicroscopy.org/pull/93. This PR updates the script to use the query returning the number of datasets in the project or plates in the screen - see https://github.com/IDR/idr.openmicroscopy.org/pull/94/commits/043e3669b6e33022ce0582c4b4d07e6c3a7b57ab.
=> stats.py: fix calculation of Sets

scripts/releases.py
Consumed by https://github.com/IDR/idr.openmicroscopy.org/pull/94 /cc @pwalczysko
=> Add first version of script computing the aggregated stats for a release

scripts/stats.py
This file was only used to return the default columns which should be largely unrelated to the computed stats.
=> Remove unnecessary check for bulk.yml

scripts/annotate/update_yeast_genes.py
Originally coming from https://github.com/IDR/idr0040-aymoz-singlecell/pull/11, this turned into a wider clean up of all yeast genome map in the IDR. Opening this as a utility script against idr-utils in case we need to update in the future
This script:
- looks for all gene map annotations containing `yeastgenome.org` in the URL
- removes all duplicate gene URLs (fixing the issue described in https://github.com/IDR/idr0040-aymoz-singlecell/pull/11)
- transforms all URLs into the canonical https://www.yeastgenome.org/locus/YBR040W
=> Yeast genes cleanup

scripts/annotate/update_compounds.py
This is part of the work on `idr0094` but like #22 was written to be run more generically.
- reviews all compound annotations, checks that no extra key exists apart from name and URL
- for all compounds with PubChem URLs, detect and report duplicate/mismatching identifiers
- update the compound URL to use the PubChem compound ID-based URL if defined and the NCBI name-based search URL otherwise
=> Add first version of script to update compounds URLs

scripts/git-restore-mtime-bare.py
- Use os.utime() follow_symlinks keyword available on Python 3
- Also decode the output of the subprocess as a string on Python 3
The usage of  `follow_symlinks` is primarily motivated by the fact that apart from the top-level `idr0015§ symlinks, all links are pointing to read-only data on NFS and this script results in `Permission Denied`.
=> Prevent git-restore-mtime-bare.py from setting timestamps on symlinks

scripts/annotate/check_annotations.py
Tries to address a few usability issues reported in https://github.com/IDR/idr-utils/pull/26#pullrequestreview-496482046 and while trying to get a sensible output.
With this PR, the `Missing Annotation` problem should now be separate from `Missing row in CSV` problem to ease debugging. Additionally, the details associated to each problem is now logged after the `ERROR` to simplify the reporting when multiple issues arise.
I have been wondering another option where the command would create a file digest of all the issues. Mostly interesting about feedback from data wranglers about this one. /cc @dominikl @pwalczysko
=> Check annotation fixes

scripts/annotate/check_annotations.py
Follow-up of #29, this adds an option allowing to produce a CSV file derived from the original passed to the `check_annotations` script with an extra column containing the details of the errors as well as extra rows for the missing annotation lines.
Testing instructions:
- create a project/dataset or a screen/plate well structure e.g.
```
project
dataset1 
image1-1.fake 
image1-2.fake 
image1-4.fake 
image1-4.fake 
dataset2
image2-1.fake 
image2-3.fake 
image2-5.fake 
```
-  create an annotation CSV with a mixture of missing rows, extra rows and duplicate rows
````csv
Image Name,Dataset Name,Channel Name
image1-1.fake,dataset1,DAPI
image1-2.fake,dataset1,GFP
image1-1.fake,dataset1,GFP
image1-3.fake,dataset1,GFP
image2-1.fake,dataset2,DAPI
image2-2.fake,dataset2,DAPI …
```
=> Check annotation report

scripts/annotate/check_annotations.py
Just two little improvements to the check_annotations.py script:
- Import the annotations.csv with default `str` data type. Otherwise plate names like '001' will be transformed to '1'.
- Add an option to prevent the entries which don't have any problems from being reported in the output csv. If there are ten thousands of entries and only a few have issues, then the output csv file is very difficult to read.
=> check_annotations improvements

pyidr/study_parser.py, scripts/stats.py
The study idr0097 to be released in the upcoming prod9  is the first example of submissions containing a mixture of screens and experiments
A few adjustments are required in the IDR utilities in order to remove the hardcoded assumption that a study is exclusively composed of screens or experiments.
- `study_parser`
- first read `Study Screens Numbers` and `Study Experiments Numbers` to determine the total number of components and adjust the regexp passed to `get_lines`
- adjust `get_lines` to return the component type found by the pattern matching
- not specific to `idr0097`, switch to HEAD for the GitHub URL to handle seamlessly repositories with either `master` or `main` as the default branch
- `stats.py`: find all folders called `screen*` or `experiment*` and determine the type per …
=> Idr0097 updates

pyidr/study_parser.py
- makes Study Organism, Experiment Organism and Screen Organism optional
- fail is both Study and Screen/Experiment have some Organism metadata
- if Study Organism is set, copy value under Screen/Experiment keys
- use Screen/Experiment keys for populating the metadata
Depends on the proposed changes in https://github.com/IDR/idr0000-lastname-example/pull/15.
See https://github.com/IDR/idr0066-voigt-mesospim/pull/6/ for a concrete application of this proposal. 
`python3 pyidr/study_parser.py /path/to/idr0066-voigt-mesospim/idr0066-study.txt --report` should set the corresponding organism for each experiment (rather than both `Mus musculus` and `Gallus gallus`).
The behavior should be unchanged for all the other studies where only `Study Organism` is defined.
=> Add support for Experiment Organism and Screen Organism keys

scripts/annotate/clean_orphaned_maps.py
Due to scaling limitations with the graph operations, the deletion of primary
map annotations can leave orphaned map annotations in the IDR database.
This script loops over the primary namespaces, queries all map annotations
attached neither to an image nor to a well and performs a delete operation on
the results using batches of 500 by default.
=> Add script to clean orphaned map annotations

pyidr/study_parser.py
As study files usually are submitted into various encoding, the study parser will regularly fail with encoding errors of type:
```
Traceback (most recent call last):
File "pyidr/study_parser.py", line 659, in <module>
parser = main(sys.argv[1:])
File "pyidr/study_parser.py", line 632, in main
p = StudyParser(s)
File "pyidr/study_parser.py", line 113, in __init__
self._study_lines = f.readlines()
File "/Users/sbesson/anaconda3/lib/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 7339: invalid start byte
```
One approach is to unify and force the encoding of study files. This PR explores the alternative approach and makes the study_parser more lenient by forcing …
=> Study parser decoding errors

scripts/create_datasets.sh
Just a little improvement for the `create_datasets.sh` script. The script assumed that the filepaths.tsv lines always starts with `Dataset:name:....`, but they can also have the format `Project:name:.../Dataset:name:...`. With this PR both formats are fine.
The later format is actually a bit pointless nowadays, because we now always use parallel imports, and the Datasets have to be pre-created in that case anyway. This can't be left to the `omero import` command any longer.
=> create_dataset.sh script

scripts/annotate/find_images.py
Script to get a list of image IDs which names match a certain regular expression. Based on (just slightly modified): https://github.com/IDR/idr0108-sabinina-nuclearporecomplex/blob/main/scripts/find_images.py) Apart from idr0108 I used it for a few other studies. Often images which need  particular rendering settings, pixel sizes, etc. set after import, can be distingushed by a common name pattern. The output can be used to successively call `omero render` etc. in for loop or used with `parallel`.
=> Add script to find images

scripts/releases.py
Previously the studies filtering was done using string comparison. Since the deployment names are now using 3 digits, the logic needs to be updated to parse the suffix and make comparison between integers
=> Update releases.py logic to cope with prod100 and greater

scripts/annotate/attach_file.py
Just noticed a little bug in the attach_file.py script. The upload-and-attach function doesn't work (does not link the file to the target) without this PR.
=> Little bugfix for the attach_file.py script

scripts/annotate/check_annotations.py
Little improvement to the check_annotations.py script. Always produce an output if the output option is specified, regardless if there were errors detected. That way you can get a list of annotations which don't match any images ("No Image"), which is not an error.
=> Output to csv even if no errors

scripts/stats.py
This adds `Sample Type` to the `stats.py` output (used to generate https://github.com/IDR/idr.openmicroscopy.org/blob/master/_data/studies.tsv).
To test on a single IDR study:
```
$ omero login
$ git clone git@github.com:IDR/idr0101-payne-insitugenomeseq.git
$ python path/to/idr-utils/scripts/stats.py --disable-fsusage
Using session for public@idr.openmicroscopy.org:4064. Idle timeout: 10 min. Current group: Public
idr0101-payne-insitugenomeseq	experimentA	TODO	2051	cell	25	0			0	156	216523	0.576208039928	576208039928			788 x 786 x 20 x 6 x 15
idr0101-payne-insitugenomeseq	experimentB	TODO	2052	tissue	57	0			0	284	2692253	10.075314787152	10075314787152			1378 x 1377 x 188 x 5 x 12
```
cc @sbesson
=> Add Sample Type to stats.py output

scripts/codon/README.md, scripts/codon/transfer.sh
As discussed yesterday, this migrate various utility scripts used on the EBI Codon SLURM cluster to idr-utils.
The initial script `transfer.sh` was used to copy ~500TB of published data onto https://ftp.ebi.ac.uk/pub/databases/IDR/
It should be used as follows
```
$ ssh ligate.ebi.ac.uk 
gate> c codon-slurm-login 
Connecting codon-slurm-login
sbesson@codon-slurm-login's password: 
...
[sbesson@codon-slurm-login-02 ~]$ become idr-virtual
[idr-virtual@codon-slurm-login-02 ~]$ ./transfer.sh idr0134-peters-bryophytes idr0134-peters-bryophytes
```
Once merged, idr-utils should be cloned in the `idr-virtual` home directory and the last command should be replaceable by
```
./idr-utils/scripts/codon/transfer.sh <source> <target>
```
=> Codon scripts

scripts/annotate/clean_orphaned_maps.py
Just noticed that there were two mapr categories missing from the cleanup script.
=> Add two missing mapr categories

scripts/annotate/set_channel_names.py
I had various variations of that in different submissions. Thought it might be a good idea to have a generic script that which works on Projects and HCS. Also replaces #41  (which took channel names from the annotated objects).
```
usage: set_channel_names.py [-h] [-v] [-s SEPARATOR] [-c COLUMN] [-d] target file
Set the channel names provided by the annotation.csv.
positional arguments:
target                Project:123 or Screen:123
file                  The annotation.csv file
options:
-h, --help            show this help message and exit
-v, --verbose         Verbosity (-v, -vv, etc)
-s SEPARATOR, --separator SEPARATOR
The separator character for the channel names (default: ;)
-c COLUMN, --column COLUMN
The name of the channels column (default: Channels)
-d, --dryrun          Don't …
```
=> Add script to set channel names
